### ISSUE TITLE
Paginate shows all results on the same page.

### ISSUE THREAD

**Issue by Fatheed7** [lixxu/flask-paginate#101]
I'm using flask-paginate for Pagination on my project, but no matter what I seem to do, I can't get it to work properly, similar to this issue (https://github.com/lixxu/flask-paginate/issues/46).

The issue was resolved, but I've not been able to get anywhere with the information that's posted as the solution and I'm hoping someone will be able to provide some insight on this, if possible.

I've got a live version hosted [here](http://formula-one-statistics.herokuapp.com/drivers)

You need to log in, but you can do so with 12345 // 12345

Thanks for any help :)

```
@app.route("/drivers")
def drivers():
    search = False
    drivers = list(mongo.db.drivers.find())
    page = request.args.get(get_page_parameter(), type=int, default=1)
    pagination = Pagination(page=page, total=len(drivers), search=search, record_name='drivers', per_page=10)
    return render_template("drivers.html", drivers=drivers, pagination=pagination)

**Comment by lixxu** [comment]
the issue is that it always shows 20 records per page?

**Comment by Fatheed7** [comment]
Apologies for not closing this issue.

I managed to resolve the issue by adapting the code from [this post.](https://gist.github.com/mozillazg/69fb40067ae6d80386e10e105e6803c9)
