### ISSUE TITLE
Page # in pagination blocks stays at 1 when two pagination blocks are used

### ISSUE THREAD

**Issue by excubo-jg** [lixxu/flask-paginate#106]
I am using two pagination blocks in my html-file and there is a problem with individually updating and preserving the respective pages.

in app.py I have:

```
def get_pagination(offset, per_page, content):
    return content[offset: offset + per_page]

@app.route('/show_ir_cases/', methods=["POST", "GET"])
def showIrCases():
    ir_cases, no_cases = some_function()
    page_ir = request.args.get(get_page_parameter('page_ir'), type=int, default=1)
    page_no = request.args.get(get_page_parameter('page_no'), type=int, default=1)
    per_page: int = 9
    offset_ir = (page_ir - 1 ) * per_page
    offset_no = (page_no - 1 ) * per_page
    pagination_ir_content = get_pagination(offset_ir, per_page, ir_cases)
    pagination_no_content = get_pagination(offset_no, per_page, no_cases)
    pagination_ir = Pagination(page=page_ir, per_page=per_page, offset=offset_ir, total=len(ir_cases), css_framework='bootstrap5', page_parameter='page_ir')
    pagination_no = Pagination(page=page_no, per_page=per_page, offset=offset_no, total=len(no_cases), css_framework='bootstrap5', page_parameter='page_no')
    return render_template('show_ir_cases.html', headers = headings, content = pagination_ir_content, content_no = pagination_no_content, pagination_ir = pagination_ir, pagination_no = pagination_no)

```
in show_ir_cases.html-file I have

`    {{ pagination_ir.links }}
`
and
`    {{ pagination_no.links }}
`

Everything is displayed correctly, the problem is that in the pagination blocks the page indicator always stays at 1. After clicking for instance "3" the data for page 3 is displayed but the indicator stays at 1. Clicking on "1" has no effect, the content is not updated and the link stays at (for instance) ?page_ir=2&page_no=3.

**Comment by lixxu** [comment]
you changed the `page_parameter` to `page_ir` and `page_no`, and you need to change the `page` parameter to `page_ir` and `page_no` in `Pagination`. like below

```
pagination_ir = Pagination(page_ir=page_ir, ...)
pagination_no = Pagination(page_no=page_no, ...)
```

**Comment by excubo-jg** [comment]
Many thanks for coming back - this fixes it. If you had the time, including the case with multiple blocks in the documentation would be marvelous as the few hints I saw on the web covering did not cover it well.
