### ISSUE TITLE
flask >= 3, from flask import Markup broken

### ISSUE THREAD

**Issue by ghmj2417** [lixxu/flask-paginate#108]
Per flask pull request, https://github.com/pallets/flask/pull/5223, Markup needs to be imported from markupsafe. flask-paginate is currently broken when using flask >= 3 because it is still trying to pull Markup from flask. https://github.com/lixxu/flask-paginate/blob/master/flask_paginate/__init__.py#L18

**Comment by NiTRoeSE** [comment]
Same problem here.. pls fix this.
Thanks in advanced!

**Comment by lixxu** [comment]
fixed. please try new release.

**Comment by ghmj2417** [comment]
I am testing it today. I will follow up when I am done.

**Comment by NiTRoeSE** [comment]
> fixed. please try new release.

Thanks, it works for me. :)
