### ISSUE TITLE
Please add an init parameter to control the url generation behavior for page 1 and prev_page

### ISSUE THREAD

**Issue by stevendavis** [lixxu/flask-paginate#111]
Please add a parameter to control the url generation behavior for page 1 and also prev_page when the prev page is 1.

There was a change many years ago here: https://github.com/lixxu/flask-paginate/pull/11/commits/dadf679c16d589f2b2dd49afa9a90bd441257234

For my application, the initial query is expensive when the page is not specified, but subsequent pagination is cheap when the page is known. I would like to expose the page number in all the pagination URLs including the page 1 link.

**Comment by lixxu** [comment]
Are you using the latest version?

**Comment by lixxu** [comment]
updated. you can pass `show_first_page_number=True` to force show page 1 link.
pypi is not available now, you may need install from github or download src to install.

**Comment by stevendavis** [comment]
Thank you for the rapid response and code change.

A couple of comments on the change:

1. I think we also need to change the prev_page() function because it checks for self.page > 2.

2. This is a minor nitpick comment, but consider calling the new parameter include_first_page_number instead of show_first_page_number. It only affects the href, not the visible rendered page.

Thank you very much for making this package available. It was a huge time-saver with so much functionality in only a few lines of code.

**Comment by lixxu** [comment]
Yes, it's a bug. Please try the updated version 2024.3.28 (pypi uploaded).
Thanks for your comments.

**Comment by stevendavis** [comment]
Tested and confirmed working as expected when include_first_page_number=True.
Thank you very much!
