### ISSUE TITLE
flask-paginate with htmx infinite scroll

### ISSUE THREAD

**Issue by JamesCHub** [lixxu/flask-paginate#114]
Possibly my expectation was incorrect, but when using mongoengine and sqlalchemy paginate, I can feed an htmx infinite scroll using a macro that looks like this
```
{% macro htmx_infinite_cards(paginate, endpoint) -%}
  {% for item in paginate.items -%}
    {% if loop.last and paginate.has_next -%}
    <div class="row"
      hx-get="{{ url_for(endpoint, page=paginate.next_num) }}"
      hx-trigger="revealed"
      hx-swap="afterend"
    >
    {% else -%}
    <div class="row">
    {% endif -%}
      {{ caller(item) }}
    </div>
  {% endfor -%}
{% endmacro -%}
```
But flask_paginate does not appear to have a next_num property, so I had to modify the macro like so:

```
{% macro htmx_infinite_cards(paginate, endpoint) -%}
  {% for item in paginate.items -%}
    {% if loop.last and paginate.has_next -%}
    <div class="row"
      hx-get="{{ url_for(endpoint, page=paginate.page+1) }}"
      hx-trigger="revealed"
      hx-swap="afterend"
    >
    {% else -%}
    <div class="row">
    {% endif -%}
      {{ caller(item) }}
    </div>
  {% endfor -%}
{% endmacro -%}
```
Did I miss something obvious here?   It's a simple workaround that seems to function as expected, so no biggie.

**Comment by lixxu** [comment]
yes, flask_paginate does not have `next_num `property, and `items `property neither. you can pull a request to add these missing properties, or I may add them in later versions.

**Comment by JamesCHub** [comment]
Okay, no worries - feel free to add my example to the docs
