### ISSUE TITLE
Generating wrong url with parameter(s)

### ISSUE THREAD

**Issue by wizcas** [lixxu/flask-paginate#24]
I come into a problem that the page links are generated incorrectly when the paginated view has parameter(s). For example, my view has following definition:

`@route('/something/<param>')`
`def something(param):`
`    ...`

and the generated url links are like this:
`http://xxxxxx/something/[u'param']?page=2`

This seems to be an issue of the `args` property, as it passes a MultiDict to `url_for` as kwargs which wrongly parses the `param` string into a list.
I solved this by changing 
```python
if PY2:
    args_items = request.args.iteritems(multi=True)
else:
    args_items = request.args.items(multi=True)
args = MultiDict(list(args_items) + list(request.view_args.items()))
```
into
```python
args_items = request.args.items()
args = dict(args_items + request.view_args.items())
```
And everything works fine.

Hope to solve this issue in new release.

**Comment by lixxu** [comment]
Is the latest version fix the issue?

**Comment by MasterMind2k** [comment]
Problem re-appears as soon as there is a multi value. I am trying to "flat" the keys. But it seems url_for, when encountering MultiDict, treats everything as a list.

**Comment by lixxu** [comment]
MasterMind2k fixed the issue.

**Comment by sparksisnotspark** [comment]
def page_href(self, page):
        if self.href:
            page = 1 if page is None else page
            url = self.href.format(page)
        else:
            url = url_for(self.endpoint, page=page, **self.args)

        # Need to return a unicode object
        return url.decode('utf8') if PY2 else url
如果有多个参数的时候，这样子会出错，
    def page_href(self, page):
        page = 1 if page is None else page
        if self.href:    
            url = self.href.format(page)
        else:
            url = url_for(self.endpoint, page=page, **self.args)

        # Need to return a unicode object
        return url.decode('utf8') if PY2 else url

这样子，就不会出错了，，，希望你再测试一下，
