### ISSUE TITLE
Won't play nice with URLs containing double quotes

### ISSUE THREAD

**Issue by afmacedo** [lixxu/flask-paginate#26]
Pagination will break if the URL contain double quotes (ie. hrefs containing JSON strings).

You should be fine using the `url_for` directly instead of unquotting it later with `urllib` in `get_link`.

Replacing:

```python
return self.get_link(url_for(self.endpoint, page=page, **self.args))
``` 

With:

```python
return url_for(self.endpoint, page=page, **self.args)
```

Did the trick for me and should not affect other cases/scenarios.

**Comment by lixxu** [comment]
urllib is introduced to deal with this issue: https://github.com/lixxu/flask-paginate/issues/21

**Comment by lixxu** [comment]
Is the new version works for your requirement?

**Comment by afmacedo** [comment]
Unfortunately it does not.
It stopped working from version 0.2.6 when ```get_link``` added the problem.

Here is an example of an url I constantly have in my project:
http://servername.com:5000/endpoint?where={"_keywords":{"$regex":"test","$options":"i"}}&sort=-end

```get_link``` will unescape whatever ```url_for``` have done, making the markup interrupt on the first occurrence of a double quote (") and creating an invalid link:
http://servername.com:5000/endpoint?where={

... that will generate an error in my backend.

**Comment by lixxu** [comment]
Please try the latest version, it should fix the issue.

**Comment by afmacedo** [comment]
Hooray, fixed! Thanks mate!
