### ISSUE TITLE
Number format total

### ISSUE THREAD

**Issue by harishvc** [lixxu/flask-paginate#29]
Number format ```total``` 

Example:

```displaying 1 - 10 records in total 1,071```

**Comment by lixxu** [comment]
Thanks for suggestion, please checkout the latest version (0.3.0) and use `format_total=True` to format total, `format_number=True` to format start and end.

**Comment by harishvc** [comment]
:thumbsup: Much appreciate your elegant solution! You can see flask-paginate in action at  [Ask GitHub](http://askgithub.com)
