### ISSUE TITLE
Please upload version 0.3.1 to PyPI.

### ISSUE THREAD

**Issue by OptiverTimAll** [lixxu/flask-paginate#31]
Version 0.3.1 has a quoting fix I'm eager to start using (thank you very much for the fix!) but although PyPI has 0.3.1 as an allowed version:

    https://pypi.python.org/pypi/Flask-paginate

...there's no downloads available for that version, which means it can't be automatically installed by tools like Pip.

**Comment by amorphic** [comment]
:+1: 

It seems like [the 0.3.1 release on PyPI](https://pypi.python.org/pypi/Flask-paginate/0.3.1) is broken. The page exists but it contains no files, so PyPI serves 0.3.0 as the latest version.

**Comment by lixxu** [comment]
0.3.1 can not be uploaded, it says already exists. So I increase the version number to 0.3.2

**Comment by OptiverTimAll** [comment]
Thank you!
