### ISSUE TITLE
Dosn't render proper bootstrap paginator

### ISSUE THREAD

**Issue by jkaberg** [lixxu/flask-paginate#35]
See screenshot below,

![image](https://cloud.githubusercontent.com/assets/613363/8915808/7ff9da48-34a7-11e5-888f-5ad3158e2115.png)

Bootstrap 3.4.4

**Comment by lixxu** [comment]
add option `css_framework='bootstrap3'` to try

**Comment by jkaberg** [comment]
thanks @lixxu , that solved it :smile:

**Comment by lixxu** [comment]
I set the option in the config file (`app.cfg`) `CSS_FRAMEWORK = 'bootstrap3'`
