### ISSUE TITLE
pagination.links的样式不对.

### ISSUE THREAD

**Issue by xegg** [lixxu/flask-paginate#37]
你好,不知道是不是因为bootstrap的版本原因,需要这样写才能够正确的显示,<ul class='pagination'>可是默认的市<div class='pagination'>.
请问这个问题应该如何解决呢?谢谢你呢

**Comment by xegg** [comment]
把我写的html给过滤掉了
```html
<ul class='pagination'>

**Comment by xegg** [comment]
不好意思,我发现只要填对版本就好了:)

**Comment by lixxu** [comment]
那我就关了，很抱歉没有及时回复。
