### ISSUE TITLE
Disabled links redirects to #

### ISSUE THREAD

**Issue by RaghavPro** [lixxu/flask-paginate#38]
When you click on a disabled link it takes you to the top of the page, because `href` is set to `#`.
It can get annoying and hurt OCD if content per page is more than 10 or 20.

A fix would be to remove the `href` attribute from disabled links.

**Comment by lixxu** [comment]
Thanks for commit, but I have to update the document, and also there's one missing for gap_markers, so I have to reject the pull request. Sorry for that.
