### ISSUE TITLE
TypeError: url_for() got multiple values for keyword argument 'page'

### ISSUE THREAD

**Issue by seantruman** [lixxu/flask-paginate#47]
`File "/opt/python-2.7.10/lib/python2.7/site-packages/flask_paginate/__init__.py", line 349, in links
    s.append(self.single_page(page) if page else self.gap_marker_fmt)
  File "/opt/python-2.7.10/lib/python2.7/site-packages/flask_paginate/__init__.py", line 323, in single_page
    return self.link.format(self.page_href(page), page)
  File "/opt/python-2.7.10/lib/python2.7/site-packages/flask_paginate/__init__.py", line 220, in page_href
    url = url_for(self.endpoint, page=page, **self.args)
TypeError: url_for() got multiple values for keyword argument 'page'`

page is already in **self.args

**Comment by lixxu** [comment]
Sorry, new version updated.

**Comment by lixxu** [comment]
should be fixed, so I close it.
