### ISSUE TITLE
After setting page_parameter to anything else other than 'page', current page is not marked active

### ISSUE THREAD

**Issue by aldacron** [lixxu/flask-paginate#50]
If you set `page_parameter` option to anything else other than the default ("page"), active breaks. In other words, suppose I set `page_parameter` to "p", no matter what page I'm on, the "active" class is always on page 1. 

I'm using bootstrap 3, but this happens with bootstrap 2 as well.

**Comment by lixxu** [comment]
What are the parameters to the `Pagination`?

**Comment by aldacron** [comment]
Sorry, it wasn't clear to me that I had to change "page" to "p" since I changed it in page_parameter. Would appreciate if this got documented!

**Comment by fzalkow** [comment]
This was also very confusing for me and should definetly be better described in the docs. For others having the problem: Instead of the `page` argument name, this argument name has to be the same as the value you pass to `page_parameter`.

Since I have multiple Paginators on the same page, I generate my pagination ids automatically. So now I end up with something like this:

    pagination_id = generate_pagination_id()  # ... generated somehow 
    page, per_page, offset = get_page_args_with_param(pagination_id)

    pagination = Pagination(total=total_items,
                            page_parameter=pagination_id,
                            **{pagination_id: page})

Also I needed to customize `get_page_args` a bit:

    # slightly modified version of flask_paginate.get_page_args to support the `param` argument
    def get_page_args_with_param(param='page'):
        args = request.args.copy()
        args.update(request.view_args.copy())
        page_parameter = args.get('page_parameter', param)
        page = int(args.get(page_parameter, 1))
        per_page = args.get('per_page')
        if not per_page:
            per_page = current_app.config.get('PER_PAGE', 10)
        else:
            per_page = int(per_page)

        offset = (page - 1) * per_page
        return page, per_page, offset

**Comment by lixxu** [comment]
I update it to version 0.5.0 which can customize `page_parameter` and `per_page_parameter`, please try.

**Comment by lixxu** [comment]
close as long time pending.

**Comment by jwitos** [comment]
Hi @lixxu, can we reopen this issue? I think the issue might still exist.

To reproduce, you can hardcode the following Pagination object:
```python
pagination = Pagination(page=5,
                        per_page=10,
                        total=1000,
                        page_parameter='p',
                        css_framework='bootstrap4')
```

Going to route with `&p=5` ignores the active page, says that it is `displaying 1 - 10 records in total 1000` and marks page 1 as active.

When changing back to:
```python
pagination = Pagination(page=5,
                        per_page=10,
                        total=1000,
                        page_parameter='page',
                        css_framework='bootstrap4')
```

it correctly displays pagination with `displaying 41 - 50 records in total 1000` and page 5 as active.

**Comment by jwitos** [comment]
@lixxu I found the problem causing this:

Pagination object is initialized and `self.page` takes a kwarg equal to `self.page_parameter`:

https://github.com/lixxu/flask-paginate/blob/6445a67395912a5432014ec824ce4bf8fd13e22d/flask_paginate/__init__.py#L313

So, if `page_parameter="p"`, Pagination will ignore `page=5` kwarg and look for `p=5`.

Changing that line to:
```python
self.page = kwargs.get("page", 1)
```

solves the problem. Happy to do a PR if you'd like.

**Comment by lixxu** [comment]
```
pagination = Pagination(p=5,
                        per_page=10,
                        total=1000,
                        page_parameter='p',
                        css_framework='bootstrap4')
```
when you set `page_parameter` to `p`, you also need to set `p=5` instead of `page=5`.

**Comment by jwitos** [comment]
@lixxu, yes, thank you. Personally I found it pretty confusing, but if you would like to keep this behavior, I would be happy to make a PR to update docs making this more clear.
