### ISSUE TITLE
why we need passing css_framework and alignment to Pagination function

### ISSUE THREAD

**Issue by alochym01** [lixxu/flask-paginate#54]
i did set the variables css_framework and alignment in the config.py file

> PER_PAGE = 10
CSS_FRAMEWORK = 'bootstrap4'
SHOW_SINGLE_PAGE = False
ALIGNMENT = 'center'
LINK_SIZE = 'sm'

and i check from app.config it did show the value for css_framework and alignment variables

> <Config {'DEBUG': True, 'TESTING': False, 'PROPAGATE_EXCEPTIONS': None, 'PRESERVE_CONTEXT_ON_EXCEPTION': None, 'SECRET_KEY': 'À\x1fPr;%2HÍ1$/©Ë\nZ\x89\x8e^2Þ»üC', 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(31), 'USE_X_SENDFILE': False, 'LOGGER_NAME': 'flask_app', 'LOGGER_HANDLER_POLICY': 'always', 'SERVER_NAME': None, 'APPLICATION_ROOT': None, 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'SEND_FILE_MAX_AGE_DEFAULT': datetime.timedelta(0, 43200), 'TRAP_BAD_REQUEST_ERRORS': False, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'JSON_AS_ASCII': True, 'JSON_SORT_KEYS': True, 'JSONIFY_PRETTYPRINT_REGULAR': True, 'JSONIFY_MIMETYPE': 'application/json', 'TEMPLATES_AUTO_RELOAD': None, 'ALIGNMENT': 'center', 'BASEDIR': '/mnt/website/WORKING/website_crawler/config', 'BCRYPT_LOG_ROUNDS': 10, 'CELERYD_LOG_FILE': '/mnt/website/WORKING/website_crawler/config/celery.log', 'CELERY_BROKER_URL': 'redis://localhost:6379/0', 'CELERY_RESULT_BACKEND': 'redis://localhost:6379/1', 'CSS_FRAMEWORK': 'bootstrap4', 'DEBUG_TB_INTERCEPT_REDIRECTS': False, 'LINK_SIZE': 'sm', 'PER_PAGE': 15, 'SHOW_SINGLE_PAGE': False, 'SQLALCHEMY_DATABASE_URI': 'sqlite:////mnt/website/WORKING/website_crawler/config/app.db', 'SQLALCHEMY_TRACK_MODIFICATIONS': False, 'TOP_LEVEL_DIR': '/mnt/website/WORKING/website_crawler', 'WTF_CSRF_ENABLED': True, 'SQLALCHEMY_BINDS': None, 'SQLALCHEMY_NATIVE_UNICODE': None, 'SQLALCHEMY_ECHO': False, 'SQLALCHEMY_RECORD_QUERIES': None, 'SQLALCHEMY_POOL_SIZE': None, 'SQLALCHEMY_POOL_TIMEOUT': None, 'SQLALCHEMY_POOL_RECYCLE': None, 'SQLALCHEMY_MAX_OVERFLOW': None, 'SQLALCHEMY_COMMIT_ON_TEARDOWN': False}>

> pagination = Pagination(page=page,per_page=per_page, record_name='vtvs', total=total)

the function did not render the html properly
to make it works. i have to set

> pagination = Pagination(css_framework='bootstrap4', page=page, alignment='center', per_page=per_page, record_name='vtvs', total=total)

**Comment by lixxu** [comment]
currently, current_app.config values not passed to the class. it only accepts the keyword parameter now.

**Comment by alochym01** [comment]
Thank you for your answer
