### ISSUE TITLE
python3.6 support

### ISSUE THREAD

**Issue by stkw0** [lixxu/flask-paginate#56]
please add support for python3.6, python3.4 is reaching the end-of-life in 2019

**Comment by lixxu** [comment]
can you try it on 3.6 and see if any errors as I don't have 3.6 projects now, thus hard to test.

**Comment by stkw0** [comment]
I tried running the tests with python3.6 and running bukuserver and seems to works.

**Comment by lixxu** [comment]
closing this as 3.6 was added to setup file.
