### ISSUE TITLE
Flask Pagination not working for Page Number 1

### ISSUE THREAD

**Issue by avinashgbhosale** [lixxu/flask-paginate#57]
Pagination working properly when we moving from page n to page 1.
For Ex:
**Case 1.**  If We move from page 1 to 2 filters are kept as it is and works properly.
**_Formed Url:_** http://localhost:5000/stats/trafficlog?page=2
**Case 2.** If We move from page 2 to others(except 1) filters are kept as it is.
**_Formed URL is_**:  http://localhost:5000/stats/trafficlog?page=50497
But not working for 
For Ex:
Case 1: If we from Other pages to page 1, it resets all filters.
**_Formed URL_**  http://localhost:5000/stats/trafficlog

But for proper pagination it should be http://localhost:5000/stats/trafficlog?page=1

Am i missing something
Please correct me

If we change the code as following working properly

![image](https://user-images.githubusercontent.com/22171537/41954723-6fa86236-79fa-11e8-83a1-788a3f2c2c89.png)

**Comment by lixxu** [comment]
`?page=1` is the default page number, so the url doesn't append it.
