### ISSUE TITLE
UndefinedError: 'flask_paginate.Pagination object' has no attribute 'skip'

### ISSUE THREAD

**Issue by zht3344** [lixxu/flask-paginate#60]
网页加上这句话会报错
<td>{{ loop.index + paginate.skip }}</td>
后台代码如下

def index():
    search = False
    q = request.args.get('q')
    if q:
        search = True
  

    page = request.args.get(get_page_parameter(), type=int, default=1)
    per_page = int(request.args.get('per_page', 2))

    print(page,per_page)
    selectdata = User.query.filter_by(password='123456').all()
    

    paginate = Pagination(page=1, total=len(selectdata), search=search, record_name='users',per_page= per_page,per_page_parameter = 'per_page')
    #paginate = selectdata.paginate(page, per_page, error_out=False)
    #stus = paginate.items

    return render_template('index.html',
                           stus=selectdata,
                           paginate=paginate,
                           )

**Comment by zht3344** [comment]
@lixxu 谢谢，更新之后没有那个错误了，但是网页仍旧显示的不对

![image](https://user-images.githubusercontent.com/25319936/52173966-9d72ce00-27c8-11e9-8148-c94418849bcf.png)
我检查了很久不知道哪里错了，能帮我看下错误吗？谢谢

`def index():
    search = False
    q = request.args.get('q')
    if q:
        search = True

    page = request.args.get(get_page_parameter(), type=int, default=1)
    per_page = int(request.args.get('per_page', 2))

    print(page,per_page)
    selectdata = User.query.filter_by(password='123456').all()
    
    paginate = Pagination(page=page, total=len(selectdata), search=search, record_name='users',per_page= per_page,per_page_parameter = 'per_page')
    return render_template('index.html',
                            page=page,
                            per_page=per_page,
                           stus=selectdata,
                           paginate=paginate,
                           )`

**Comment by lixxu** [comment]
css框架用的哪个? 默认是`bootstrap2`

**Comment by zht3344** [comment]
用的是默认的，会有错误吗

**Comment by lixxu** [comment]
那你的html里引用了`bootstrap2`了吗?有它对应的css文件等了吗?

**Comment by zht3344** [comment]
第一页，第二页显示的内容一样😂
![image](https://user-images.githubusercontent.com/25319936/52174585-15dd8d00-27d1-11e9-83c8-db5a95ecc227.png)
![image](https://user-images.githubusercontent.com/25319936/52174587-1c6c0480-27d1-11e9-8a2d-697b69e86093.png)

**Comment by lixxu** [comment]
先把前端的弄正确了再说

**Comment by zht3344** [comment]
前端的现在格式对了，是bootstrap4的
![image](https://user-images.githubusercontent.com/25319936/52174854-30196a00-27d5-11e9-9731-14bfd482c498.png)

![image](https://user-images.githubusercontent.com/25319936/52174846-15df8c00-27d5-11e9-8bff-a146755117b7.png)
但是显示的信息条数还是不对😥，正确的应该是每页有两条信息

**Comment by lixxu** [comment]
数据查询时没有作分页处理.

**Comment by zht3344** [comment]
谢谢，问题解决了，😁
