### ISSUE TITLE
about search

### ISSUE THREAD

**Issue by 0428** [lixxu/flask-paginate#63]
i have a problem about search,firstly, about how to configure,i see few aspect about search on the docs and i see the souce code there are two parameters(`search` and `found`),so i want to know how configure search.secondly,it's about the search result. is there only one display result that is on the docs that `found <b>{found}</b> {record_name}, displaying <b>{start} - {end}</b>` ?can it show results in the table after searching?

**Comment by lixxu** [comment]
the `search` and `found` are just display text, not for searching
