### ISSUE TITLE
Wrong pagnitation style

### ISSUE THREAD

**Issue by ystreibel** [lixxu/flask-paginate#64]
Hi,

I tried to use this library and I have this:

![Capture d’écran 2019-06-12 à 16 14 22](https://user-images.githubusercontent.com/3459111/59358604-2c6e9480-8d2d-11e9-93c2-89204110bdde.png)

What I have missed ?

**Comment by ystreibel** [comment]
I found the workaround by add `css_framework='bootstrap4'` in `Pagination` call.

**Comment by aloneGH** [comment]
You can try to replace `css_framework` to `'bootstrap'`, and also add `'bs_version=4'`
