### ISSUE TITLE
分页的时候，省略的部分错误，导致会多一行。我用的是bootstrap3.7

### ISSUE THREAD

**Issue by lovefox666** [lixxu/flask-paginate#66]
![image](https://user-images.githubusercontent.com/34913809/60385632-ca988380-9abd-11e9-90c5-ba359d928a09.png)

**Comment by lixxu** [comment]
能把生成的html源码贴出来看一下吗? 我这里没有测试环境. 另外, 是3.3.7版本吧? 官网没看到有3.7版本

**Comment by lovefox666** [comment]
<!DOCTYPE html>
<html lang="zh-CN">
<head>


<title>
		工单列表
	</title>




    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	
	<link href="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
	
	<link rel="stylesheet" href="/static/plugin/loading/css/fakeLoader.css">
    <link rel="stylesheet" href="/static/css/loading.css">
 	<link rel="icon" type="image/png" sizes="16x16" href="/static/fav.png">
	


</head>


<body>
    
    <div class="dailog_loading">
        <div>
            <b></b>
        </div>
    </div>
	<nav class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/reception">
					<img alt="Brand" width="20" height="20" src="/static/fav.png">
				</a>
			</div>


			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li>
						<a href="/reception">
							<span class="glyphicon glyphicon-home"></span> 首页
						</a>
					</li>
				</ul>


				<ul class="nav navbar-nav navbar-right">
						<li><a href=""><span class="glyphicon glyphicon-question-sign"></span> 帮助</a></li>
					
						<li><a href=""><span class="glyphicon glyphicon-list-alt"></span> 档案</a></li>
						<li><a href=""><span class="glyphicon glyphicon-log-out"></span> 退出</a></li>
					
				</ul>
			</div>
		</div>
	</nav>






	<div class="container">
		
			
		


		
		




    <ul class="pagination"><li class="previous disabled unavailable"><a> � </a></li><li class="active"><a>1</a></li><li><a href="/reception/category?category_type=owner&page=2">2</a></li><li><a href="/reception/category?category_type=owner&page=3">3</a></li><li><a href="/reception/category?category_type=owner&page=4">4</a></li><li><a href="/reception/category?category_type=owner&page=5">5</a></li><li class="disabled"><a>...</a></li><li><a href="/reception/category?category_type=owner&page=17">17</a></li><li><a href="/reception/category?category_type=owner&page=18">18</a></li><li class="next"><a href="/reception/category?category_type=owner&page=2">�</a></li></ul>




    
    
        <div class="panel  panel-success ">
            <div class="panel-heading">
                <h3 class="panel-title">
                    
                    已办结
                    
                    <div style="display:flex; float: right;">
                        <form action="/reception/ticket/58" method="GET">
                            <button type="submit" class="btn btn-warning btn-xs">查看详情</button>
                        </form>
                    </div>
                </h3>
            </div>
            <ul class="list-group">
                    <li class="list-group-item">申请类别：业务接待</li>
                <li class="list-group-item">申请事项：测试策划部门审批</li>
                <li class="list-group-item">
                    申请人：张三，
                    <a href="tel://133">
                        <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>
                        13365915511
                    </a>
                </li>
                <li class="list-group-item">申请时间：2019-06-29 11:37:31</li>
                
            </ul>
        </div>
    
        <div class="panel  panel-primary ">
            <div class="panel-heading">
                <h3 class="panel-title">
                    
                    当前流程：部门主任审批
                    
                    <div style="display:flex; float: right;">
                        <form action="/reception/ticket/54" method="GET">
                            <button type="submit" class="btn btn-warning btn-xs">查看详情</button>
                        </form>
                    </div>
                </h3>
            </div>
            <ul class="list-group">
                    <li class="list-group-item">申请类别：业务接待</li>
                <li class="list-group-item">申请事项：睡前测试一下</li>
                <li class="list-group-item">
                    申请人：张三，
                    <a href="tel://1336">
                        <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>
                        13365915511
                    </a>
                </li>
                <li class="list-group-item">申请时间：2019-06-29 00:44:25</li>
                
            </ul>
        </div>
    






    <ul class="pagination"><li class="previous disabled unavailable"><a> � </a></li><li class="active"><a>1</a></li><li><a href="/reception/category?category_type=owner&page=2">2</a></li><li><a href="/reception/category?category_type=owner&page=3">3</a></li><li><a href="/reception/category?category_type=owner&page=4">4</a></li><li><a href="/reception/category?category_type=owner&page=5">5</a></li><li class="disabled"><a>...</a></li><li><a href="/reception/category?category_type=owner&page=17">17</a></li><li><a href="/reception/category?category_type=owner&page=18">18</a></li><li class="next"><a href="/reception/category?category_type=owner&page=2">�</a></li></ul>






	</div>






	
	
	<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
	
	<script src="/static/plugin/loading/js/fakeLoader.min.js"></script>
	
	<script src="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
	
    <script>
        $(window).load(function(){
            $('[data-toggle="tooltip"]').tooltip('show');
            $('.dailog_loading').fadeOut(500)
        })
    </script>




</body>
</html>



在手机移动端出现问题，PC端，我没有那么多数据，暂时无法开出问题。








------------------ 原始邮件 ------------------
发件人: "Lix Xu"<notifications@github.com>;
发送时间: 2019年6月30日(星期天) 上午9:29
收件人: "lixxu/flask-paginate"<flask-paginate@noreply.github.com>;
抄送: "夜凉如水"<540085660@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lixxu/flask-paginate] 分页的时候，省略的部分错误，导致会多一行。我用的是bootstrap3.7 (#66)




能把生成的html源码贴出来看一下吗? 我这里没有测试环境. 另外, 是3.3.7版本吧? 官网没看到有3.7版本

**Comment by lixxu** [comment]
bootstrp 3.3 版本在分页开始处加了`<nav aria-label="Page navigation example">`, 稍后我会更新.

**Comment by lixxu** [comment]
发了`0.5.3`, 但没验证是否可行, 配置文件里用 `CSS_FRAMEWORK = "bootstrap3_3"`, 参数形式时用`css_framework = "bootstrap3_3"`指定版本

**Comment by lixxu** [comment]
可能是手机浏览器的问题吧, 我把你贴的存成html文件, 电脑上打开是正常的, 上面加了<nav>, 下面的没加, 都没有出现你说的问题.
![image](https://user-images.githubusercontent.com/264487/60393479-bc437980-9b48-11e9-8cd0-8843b05560d3.png)

**Comment by lixxu** [comment]
上面加了`<nav>`, 下面的没加, 都没有出现你说的问题.

**Comment by lovefox666** [comment]
如何更新包？

还是0.5.2




------------------ 原始邮件 ------------------
发件人: "Lix Xu"<notifications@github.com>;
发送时间: 2019年6月30日(星期天) 下午3:00
收件人: "lixxu/flask-paginate"<flask-paginate@noreply.github.com>;
抄送: "夜凉如水"<540085660@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lixxu/flask-paginate] 分页的时候，省略的部分错误，导致会多一行。我用的是bootstrap3.7 (#66)




发了0.5.3, 但没验证是否可行, 配置文件里用 CSS_FRAMEWORK = "bootstrap3_3", 参数形式时用css_framework = "bootstrap3_3"指定版本

**Comment by lixxu** [comment]
`pip install -U flask-paginate`
![image](https://user-images.githubusercontent.com/264487/60394616-89ee4800-9b59-11e9-8fe9-fad13170a6b8.png)

**Comment by lovefox666** [comment]
问题依旧。是不是需要修改什么地方的配置啊。我除了更新没有修改配置。
------------------ 原始邮件 ------------------
发件人: "Lix Xu"<notifications@github.com>;
发送时间: 2019年6月30日(星期天) 下午5:07
收件人: "lixxu/flask-paginate"<flask-paginate@noreply.github.com>;
抄送: "夜凉如水"<540085660@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lixxu/flask-paginate] 分页的时候，省略的部分错误，导致会多一行。我用的是bootstrap3.7 (#66)




pip install -U flask-paginate

**Comment by lixxu** [comment]
估计是浏览器的问题了, 不过看起来是宽度不够换行了. 是不是布局哪里设置的问题?

**Comment by lovefox666** [comment]
我是google浏览器和手机安卓都是这样。------------------ 原始邮件 ------------------
发件人: "Lix Xu"<notifications@github.com>
发送时间: 2019年7月1日(星期一) 上午7:37
收件人: "lixxu/flask-paginate"<flask-paginate@noreply.github.com>;
抄送: "莫失莫忘"<540085660@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lixxu/flask-paginate] 分页的时候，省略的部分错误，导致会多一行。我用的是bootstrap3.7 (#66)



估计是浏览器的问题了, 不过看起来是宽度不够换行了. 是不是布局哪里设置的问题?
 
&mdash;

**Comment by lixxu** [comment]
可是你看我的截图, 我只是把你贴出来的html存到文件里, 打开显示很正常啊.

**Comment by lovefox666** [comment]
是不是因为你的没有切换手机模式。谷歌按F12，选手机模式试试------------------ 原始邮件 ------------------
发件人: "Lix Xu"<notifications@github.com>
发送时间: 2019年7月1日(星期一) 上午8:14
收件人: "lixxu/flask-paginate"<flask-paginate@noreply.github.com>;
抄送: "莫失莫忘"<540085660@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lixxu/flask-paginate] 分页的时候，省略的部分错误，导致会多一行。我用的是bootstrap3.7 (#66)



可是你看我的截图, 我只是把你贴出来的html存到文&#x4EF6;里, 打开显示很正常啊.
 
&mdash;

**Comment by lixxu** [comment]
像这样的? 这就是宽度不够导致的, 看截图不同的手机尺寸, 显示就不一样
![image](https://user-images.githubusercontent.com/264487/60405039-56a2cc00-9be0-11e9-8657-9c8e5e7c63af.png)
![image](https://user-images.githubusercontent.com/264487/60405050-6e7a5000-9be0-11e9-809f-632d8a2daaee.png)

**Comment by lovefox666** [comment]
bootstrap不是能自适应么？------------------ 原始邮件 ------------------
发件人: "Lix Xu"<notifications@github.com>
发送时间: 2019年7月1日(星期一) 上午9:14
收件人: "lixxu/flask-paginate"<flask-paginate@noreply.github.com>;
抄送: "莫失莫忘"<540085660@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lixxu/flask-paginate] 分页的时候，省略的部分错误，导致会多一行。我用的是bootstrap3.7 (#66)



像这样的? 这就是宽度不够导致的, 看截图不同的手机尺寸, 显示就不一样
 
 
 
&mdash;

**Comment by lixxu** [comment]
这已经是自适应了吧

**Comment by lovefox666** [comment]
我理解的是，根据手机宽度自适应一行。------------------ 原始邮件 ------------------
发件人: "Lix Xu"<notifications@github.com>
发送时间: 2019年7月1日(星期一) 上午9:22
收件人: "lixxu/flask-paginate"<flask-paginate@noreply.github.com>;
抄送: "莫失莫忘"<540085660@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lixxu/flask-paginate] 分页的时候，省略的部分错误，导致会多一行。我用的是bootstrap3.7 (#66)



这已经是自适应了吧
 
&mdash;

**Comment by lixxu** [comment]
意思是根据宽度自动调整字体大小?

**Comment by lovefox666** [comment]
字体倒是不要，而是根据宽度自动适应页码数量吧。目前的情况，是下一页这个会跑到下一行。只要把中间显示的页码少一个就好。宽度获取出来后，减去上一页下一页两个按钮，中间的部分除以每个按钮宽度，得出中间有多少个。。。 不懂我说的对不对。这样就是一行。------------------ 原始邮件 ------------------
发件人: "Lix Xu"<notifications@github.com>
发送时间: 2019年7月1日(星期一) 上午10:39
收件人: "lixxu/flask-paginate"<flask-paginate@noreply.github.com>;
抄送: "莫失莫忘"<540085660@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lixxu/flask-paginate] 分页的时候，省略的部分错误，导致会多一行。我用的是bootstrap3.7 (#66)



意思是根据宽度自动调整字体大小?
 
&mdash;

**Comment by lixxu** [comment]
分页的html是已经生成的, 没办法知道设备尺寸, 而且这也不是它该做的事情, 它只是分页用的啊. 
这个问题不是扩展的问题了, 就此结贴了. 
你可以试试调整一下 `inner_window` 和 `outer_window`的数字看看有没有改善. 但如果能改善也是治标不治本, 因为如果页数是个很大的数字时 比如第`1234567` 页, 也许两个就占满屏幕了.
