### ISSUE TITLE
Include test script to pypi release

### ISSUE THREAD

**Issue by stkw0** [lixxu/flask-paginate#68]
Please include tests scripts on the next pypi release, it will make it easier for maintainers. Also I think it can be useful to also create github tags for the releases¿?

Thank you.

**Comment by sbraz** [comment]
In order to add tests, you'd only need to add this to `MANIFEST.in` (adding docs is a good idea too):
```
graft docs tests
global-exclude __pycache__
global-exclude *.py[co]
```

**Comment by lixxu** [comment]
could you help to submit PR for this, as I can not do it now.

**Comment by sbraz** [comment]
Thanks, I forgot to make that PR.

Could you add tags to git for the last version and future versions? It's provides a nice way to view changes between versions.
