### ISSUE TITLE
is it possible to disable the default url encoding in pagination.links?

### ISSUE THREAD

**Issue by tmerkaj** [lixxu/flask-paginate#74]
We do have the urls encoded  and the pagination does another encoding on the already encoded url.

**Comment by lixxu** [comment]
please try version `0.5.5` and pass the argument `url_coding=None` to disable it.

**Comment by tmerkaj** [comment]
Thanks for your quick reply, Just tried that, unfortunately didn’t fix the issue.

**Comment by tmerkaj** [comment]
Thanks for your quick reply, Just tried that, unfortunately didn’t fix the issue.

**Comment by lixxu** [comment]
IMO, `url_for` does not have option to disable encode. you may turn to [https://github.com/pallets/flask/issues](https://github.com/pallets/flask/issues) for help.

**Comment by tmerkaj** [comment]
ok thanks
