### ISSUE TITLE
Issue with paginate links and css

### ISSUE THREAD

**Issue by sergiodevelop78** [lixxu/flask-paginate#79]
Hello, Im using your great code, and it works great with the core function (pagination)

Im only have a problem, with the pagination links: there is no way to use Bootstrap 4 styles.
I'm getting a vertical list of links.

I will appreciate you can help me

Thanks.

Sergio

This is my code on Flask 

    return render_template('usuarios/listusers.html', 
                title="Listado de Usuarios", datos = datos_filtrados, \
                pagination=pagination, bs_version='4', css_framework='bootstrap')

**Comment by sergiodevelop78** [comment]
This is the HTML generated with Python - Flask and your app.


<div class="pagination-page-info">displaying <b>1 - 5</b> datos in
--
  | total <b>9</b></div><div class="pagination"><ul><li class="previous disabled unavailable"><a> &laquo; </a></li><li class="active"><a>1</a></li><li><a href="/listusers?page=2">2</a></li><li class="next"><a href="/listusers?page=2">&raquo;</a></li></ul></div>

**Comment by lixxu** [comment]
`bs_version` is a parameter passed to `Pagination` class.

**Comment by sergiodevelop78** [comment]
> `bs_version` is a parameter passed to `Pagination` class.
> e.g. `pagination = Pagination(..., css_framework='bootstrap4')`

Hi i tried but nothing changed. Here is the result:


<div class="pagination-page-info">displaying <b>1 - 5</b> datos in
--
  | total <b>9</b></div><div class="pagination"><ul><li class="previous disabled unavailable"><a> &laquo; </a></li><li class="active"><a>1</a></li><li><a href="/listusers?page=2">2</a></li><li class="next"><a href="/listusers?page=2">&raquo;</a></li></ul></div>

**Comment by lixxu** [comment]
`css_framework` is not the parameter to `render_template`, it's used for creating `pagination` instance.
e.g.
```
pagination = Pagination(..., css_framework='bootstrap4')

return render_template(
    'usuarios/listusers.html',
    title="Listado de Usuarios",
    datos = datos_filtrados,
    pagination=pagination
)
```

**Comment by sergiodevelop78** [comment]
Thank you very much !!! Now it works great !!
