### ISSUE TITLE
how to add pagination in app with search form? 

### ISSUE THREAD

**Issue by Merajit** [lixxu/flask-paginate#82]

**Comment by lixxu** [comment]
because you're using POST method, you should use GET method as search will not generate or update any data

**Comment by Merajit** [comment]
![image](https://user-images.githubusercontent.com/18600353/83995934-6bebb300-a978-11ea-9821-7d7d0dbc4a66.png)

**Comment by Merajit** [comment]
> because you're using POST method, you should use GET method as search will not generate or update any data

I am new in flask. 
if I will not use post then how my form will work.
can you check my code and correct it.
It will be very helpful to me.
thanks in advance.

**Comment by lixxu** [comment]
```
toolName = request.args.get("toolName")
solution_data = solution_result(toolName)
```
`<form  name="searchForm" action="{{ url_for('home') }}" method="GET" >`

**Comment by Merajit** [comment]
> ```
> toolName = request.args.get("toolName")
> solution_data = solution_result(toolName)
> ```
> 
> `<form name="searchForm" action="{{ url_for('home') }}" method="GET" >`

now search functionality is not working?
any idea?

![image](https://user-images.githubusercontent.com/18600353/83997999-44e3b000-a97d-11ea-8a82-c10ab26cc028.png)

Thanks in advance

**Comment by lixxu** [comment]
```
pagination = Pagination(page=page, per_page=per_page, found=len(result), total=len(total), 
	record_name='products',css_framework='bootstrap3', search=toolName)
```

**Comment by Merajit** [comment]
> ```
> pagination = Pagination(page=page, per_page=per_page, found=len(total), total=len(total), 
> 	record_name='products',css_framework='bootstrap3', search=toolName)
> ```

not working!!

**Comment by lixxu** [comment]
`toolName = request.args.get("toolname")`

**Comment by Merajit** [comment]
> `toolName = request.args.get("toolname")`

Hello Dear,

It is not working.

Please help with the search form pagination in your module. it will help many people.

**Comment by lixxu** [comment]
can you paste your latest code?

**Comment by Merajit** [comment]
> can you paste your latest code?

Hi,
Please find below

**main. py**

    from flask import Flask, render_template, request, jsonify, redirect, url_for
    import flask
    from flask_paginate import Pagination, get_page_parameter
    import json
    import dbConnect
    import datetime
    
    app = Flask(__name__)
    app.secret_key = "logger@!#$%^"
    
    @app.route("/home",methods=['GET','POST'])
    def home():
    	toolName = None
    	if "toolname" in request.form:
    		#toolName = request.form["toolname"]
			toolName = request.args.get("toolName")
    		
    	solution_data = solution_result(toolName)
    	return render_template("home.html",solution_data=solution_data[0],pagination=solution_data[1])
    
    			
    def solution_result(toolName):
        
    	# Setting page, limit and offset variables
    	per_page = 2
    	page = request.args.get(get_page_parameter(), type=int, default=1)
    	offset = (page - 1) * per_page
    	
    	cursor = dbConnect.ConnectDatabase()
    	
    	# Executing a query to get the total number of products
    	if toolName:
    		total_sql = sql = "select tool from error_history where tool=%s"
    		cursor.execute(total_sql,(toolName))
    		total = cursor.fetchall()
    	else:
    		total_sql = sql = "select tool from error_history"
    		cursor.execute(total_sql)
    		total = cursor.fetchall()
    	
    	# execute SQL query using execute() method.
    	if toolName:
    		sql = "select id, tool, error from error_history where tool=%s ORDER BY id DESC LIMIT %s OFFSET %s"
    		cursor.execute(sql,(toolName,per_page, offset))
    	else:
    		sql = "select id, tool, error from error_history ORDER BY id DESC LIMIT %s OFFSET %s"
    		cursor.execute(sql,(per_page, offset))
    	
    	result = cursor.fetchall()
    	
    	# Setting up the pagination variable, where you are using len(total) to set the total number of 
    	# items available
    	#pagination = Pagination(page=page, per_page=per_page, offset=offset, total=len(total), record_name='products',css_framework='bootstrap3')
    	pagination = Pagination(page=page, per_page=per_page, found=len(total), total=len(total), record_name='products',css_framework='bootstrap3', search=toolName)
		
    	dbConnect.closeConnection()
    	return result, pagination
    	
    if __name__ == "__main__":
        app.run(debug=True)

	
**dbConnect.py**

    import pymysql
    client = None
    def ConnectDatabase():
        try:
            global client
            # Open database connection
            client = pymysql.connect("localhost","root","","solution")
            # makes autocommit false
            client.autocommit(False)
            # prepare a cursor object using cursor() method
            cursor = client.cursor()
            #print("******** database connected ****")
            return cursor
        except:
            print("******** database not connected ****")
            
    def closeConnection():
        global client
        client.close()
           
    if __name__ == "__main__":
        ConnectDatabase()


**solution.error_history table**

    CREATE TABLE `error_history` (
      `id` int(11) NOT NULL,
      `tool` varchar(255) NOT NULL,
      `error` varchar(255) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    
    INSERT INTO `error_history` (`id`, `tool`, `error`) VALUES
    (1, 'tool1', 'error in toola'),
    (2, 'tool2', 'error in toole'),
    (3, 'tool3', 'error in place'),
    (4, 'tool1', 'error in toolh'),
    (5, 'tool1', 'error in toolo'),
    (6, 'tool1', 'error in tool123'),
    (7, 'tool1', 'error in toolxy'),
    (8, 'tool2', 'error in toolxyz');
    
    ALTER TABLE `error_history`
      ADD PRIMARY KEY (`id`);
    
    ALTER TABLE `error_history`
      MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

  
**home.html**

    <!DOCTYPE html>
    <html lang="en" dir="DataLogger">
      <head>
        <meta charset="utf-8">
        <title>Data</title>
    	
    	<style>
    		.pagination-page-info {
    			padding: .6em;
    			padding-left: 0;
    			width: 40em;
    			margin: .5em;
    			margin-left: 0;
    			font-size: 12px;
    		}
    		.pagination-page-info b {
    			color: black;
    			background: #6aa6ed;
    			padding-left: 2px;
    			padding: .1em .25em;
    			font-size: 150%;
    		}
    	</style>
      </head>
      <body>
       <div class="wrapper">
        {% block content %}
        
         <div id="Sidebar">
         
         </div>
        
        
         <div id="content" >
      		
       		
           
           	<p class="" style="font-weight: bold;">Dashboard</p>
           	
           	<div class="row">
    			<form  name="searchForm" action="{{ url_for('home') }}" method="GET" >
    				<div class="form-group col-xs-10 col-sm-4 col-md-4 col-lg-4">
                       <input type="input" class="form-control" id="toolname" name="toolname" placeholder="Search tool"
                              value="" required>
                    </div>
                    <div class="form-group col-xs-10 col-sm-4 col-md-4 col-lg-4">
                    	<button type="submit" class="btn btn-primary">Search</button>
                    </div>
    	        </form>
    	    </div>
           	
           
           	<div class="row col-xs-10 col-sm-4 col-md-4 col-lg-12">
           		{{ pagination.info }}
           	</div>
    		<div class="row  table-responsive col-xs-10 col-sm-4 col-md-4 col-lg-12">
    			
       			<table class="table table-bordered solutionTable ">
    		    <thead class="">
    		      <tr>
    		        <th>Sl No.</th>
    		        <th>Tool</th>
    		        <th>error</th>
    		      </tr>
    		    </thead>
    		    <tbody>
    		    	{% for row in solution_data %}
    			    	 
    		    		<tr>
    				      	<td>{{loop.index + (pagination.page - 1) * pagination.per_page }}</td>
    				      	<td>{{ row[1] }}</td>
    				      	<td>{{ row[2] }}</td>
    				     </tr>
    		    	{% endfor %}
    		    </tbody>
    		  </table>
    		  
    		</div>
    		<div class="row  col-xs-10 col-sm-4 col-md-4 col-lg-12">
    			{{ pagination.links }}
    		</div>
    		 
    	</div>
         {% endblock %}
      </body>
    </html>

**Comment by lixxu** [comment]
change
 ```
if "toolname" in request.form:
    #toolName = request.form["toolname"]
    toolName = request.args.get("toolName")
```
to
`toolName = request.args.get("toolName")`

**Comment by Merajit** [comment]
> change
> 
> ```
> if "toolname" in request.form:
>    #toolName = request.form["toolname"]
>    toolName = request.args.get("toolName")
> ```
> 
> to
> `toolName = request.args.get("toolName")`

Hi,

It is not working as expected.

**Comment by lixxu** [comment]
can you print `toolName `after `toolName = request.args.get("toolName")` to see its value?

**Comment by Merajit** [comment]
> sorry, should be `toolname` in `toolName = request.args.get("toolname")`

Hi 
it didn't worked.

I did with SQLAlchemy, and it is working as expected.  

I am not using "flask paginate" module.

Thanks
