### ISSUE TITLE
Possible pagination bug?

### ISSUE THREAD

**Issue by bvasiles** [lixxu/flask-paginate#83]
Hi there! Thanks for this package.

Should [this](https://github.com/lixxu/flask-paginate/blob/6445a67395912a5432014ec824ce4bf8fd13e22d/flask_paginate/__init__.py#L319) be `self.per_page = kwargs.get(per_page, 10)` instead?

Otherwise it seems to default to 10 no matter what you set `per_page` to.

**Comment by lixxu** [comment]
`per_page_param` is the name for `per_page parameter`, default is `per_page`

**Comment by bvasiles** [comment]
Okay, I see.

Does that mean one has to always set `per_page_parameter` whenever calling the constructor?

**Comment by lixxu** [comment]
default is `per_page`

**Comment by bvasiles** [comment]
Ok, thanks for clarifying. I probably missed it.
