### ISSUE TITLE
Translate text shown in {{ pagination.info }}

### ISSUE THREAD

**Issue by mflpopescu** [lixxu/flask-paginate#92]
Is there a parameter to translate the text under {{ pagination.info }} ? The language of the website is not English so wondering if the text _displaying 21 - 30 records in total 45_ can be translated.

**Comment by lixxu** [comment]
you can pass the translated text template to `Pagination class`.
e.g. `Pagination(display_msg='translated text')`

**Comment by mflpopescu** [comment]
thanks, that works
