### ISSUE TITLE
Does it only work for python Sql module?

### ISSUE THREAD

**Issue by saleem8054** [lixxu/flask-paginate#97]
Hi,
Does this application work for Flask Sqlalchemy or List in python. If it does then can you please show the example of it?
I personally tried many times but could not figure it out.
Thank you.

**Comment by lixxu** [comment]
The `Pagination` class needs `per_page, page, total` arguments to create instance, so it will work if you pass the needed args to it. You can check the example code to see how it work. Or, please paste your code then we can see how it going.

**Comment by lixxu** [comment]
closed as long time feedback.
